package entidades;
// Generated 13/05/2019 09:34:46 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idProducto;
     private Categoria categoria;
     private String nombre;
     private BigDecimal precio;
     private String marca;
     private int stock;
     private Set detalleventas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(int idProducto, Categoria categoria, String nombre, BigDecimal precio, String marca, int stock) {
        this.idProducto = idProducto;
        this.categoria = categoria;
        this.nombre = nombre;
        this.precio = precio;
        this.marca = marca;
        this.stock = stock;
    }
    public Producto(int idProducto, Categoria categoria, String nombre, BigDecimal precio, String marca, int stock, Set detalleventas) {
       this.idProducto = idProducto;
       this.categoria = categoria;
       this.nombre = nombre;
       this.precio = precio;
       this.marca = marca;
       this.stock = stock;
       this.detalleventas = detalleventas;
    }
   
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


