package entidades;
// Generated 13/05/2019 09:34:46 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ventas generated by hbm2java
 */
public class Ventas  implements java.io.Serializable {


     private int idVentas;
     private BigDecimal total;
     private Date fecha;
     private Set detalleventas = new HashSet(0);

    public Ventas() {
    }

	
    public Ventas(int idVentas, BigDecimal total, Date fecha) {
        this.idVentas = idVentas;
        this.total = total;
        this.fecha = fecha;
    }
    public Ventas(int idVentas, BigDecimal total, Date fecha, Set detalleventas) {
       this.idVentas = idVentas;
       this.total = total;
       this.fecha = fecha;
       this.detalleventas = detalleventas;
    }
   
    public int getIdVentas() {
        return this.idVentas;
    }
    
    public void setIdVentas(int idVentas) {
        this.idVentas = idVentas;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


